---
- name: Install PostgreSQL cluster members
  hosts: "{{ _postgresql_db_group }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Deploy PostgreSQL repo
      ansible.builtin.include_role:
        name: nephelaiio.postgresql.repo
